name: EbdGNN
normalize: true
loop: true
params:
  gcn:
    gnn_type: gcn
    architecture:
      num_layers: 2
      hidden_channels: 64
      dropout: 0.5
      batch_norm: true
      residual: false
    optim: adam
    lr: 0.01
    epochs: 1000
    pepochs: 128
    bepochs: 128
    adjust_lr: false
    use_labels: false
    log_steps: 1

  gcn2:
    gnn_type: gcn2
    architecture:
      num_layers: 2
      hidden_channels: 64
      dropout: 0.5
      batch_norm: true
      residual: false
      alpha: 0.2
      theta: 0.5
    optim: adam
    lr: 0.01
    epochs: 1500
    pepochs: 128
    bepochs: 128
    log_steps: 1
    adjust_lr: false
    use_labels: false

  sgc:
    gnn_type: sgc
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.1
      batch_norm: true
    optim: adam
    lr: 0.01
    epochs: 1500
    pepochs: 128
    bepochs: 128
    log_steps: 1

  appnp:
    gnn_type: appnp
    architecture:
      num_layers: 2
      hidden_channels: 128
      alpha: 0.5
      dropout: 0.5
      batch_norm: true
    optim: adam
    lr: 0.001
    epochs: 1200
    pepochs: 128
    bepochs: 128
    log_steps: 1

  gat:
    gnn_type: gat
    architecture:
      num_layers: 2
      hidden_channels: 128
      dropout: 0.5
      batch_norm: true
      residual: true
    optim: rmsprop
    lr: 0.01
    epochs: 1500
    pepochs: 128
    bepochs: 10
    log_steps: 1
    #sp 0.1