name: SAGE
loop: false
normalize: false
architecture:
  num_layers: 2
  hidden_channels: 128
  dropout: 0.5
  batch_norm: false
  residual: false

grad_norm: 0.5
optim: adam
# edge_drop: 0.0
lr: 0.002
epochs: 500
log_steps: 1